source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'pg'

gem 'grape'
gem 'grape-swagger-rails'
gem 'grape-entity'
gem 'rack-cors'
gem 'hashie-forbidden_attributes'

group :development do
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
end
